language: android
jdk: oraclejdk11
sudo: required

env:
  global:
    - ANDROID_API_LEVEL=33
    - ANDROID_BUILD_TOOLS_VERSION=33.0.0 # Ensure this matches your build tools version

android:
  components:
    - tools
    
before_install:
  # Install cmdline-tools (older tools doesn't support Java 11)
  - wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O android-commandline-tools-linux.zip
  - mkdir -p ${ANDROID_HOME}/cmdline-tools
  - unzip -q android-commandline-tools-linux.zip -d ${ANDROID_HOME}/cmdline-tools
  - mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest

before_script:
  - echo y | ${TOOLS}/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "tools" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "build-tools;$BUILD_TOOLS" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "platforms;android-$BUILD_API" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "extras;android;m2repository" >/dev/null

  
script:
  # Build the app and run unit tests
  - ./gradlew clean build test
