language: android
jdk: oraclejdk11
sudo: required

env:
  global:
    - ANDROID_API_LEVEL=33
    - ANDROID_BUILD_TOOLS_VERSION=33.0.0 # Ensure this matches your build tools version

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-m2repository

script:
  # Build the app and run unit tests
  - ./gradlew clean build test
